name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        rust: [stable, 1.75.0]
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - arm-unknown-linux-gnueabi # Raspberry Pi 1
          - armv7-unknown-linux-gnueabihf # Raspberry Pi 2, 3, etc
          # Bare metal
          - thumbv6m-none-eabi
          - thumbv7em-none-eabi
          - thumbv7em-none-eabihf
          - thumbv7m-none-eabi
    uses: eldruin/rust-driver-ci-scripts/.github/workflows/build.yml@v1
    with:
      rust: ${{ matrix.rust }}
      target: ${{ matrix.target }}

  checks:
    uses: eldruin/rust-driver-ci-scripts/.github/workflows/check.yml@v1
    with:
      clippy-version: 1.87.0

  test:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
    uses: eldruin/rust-driver-ci-scripts/.github/workflows/test.yml@v1
    with:
      rust: stable
      target: ${{ matrix.target }}